name: real_estate_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  google_maps_flutter: ^2.10.1
  widget_to_marker: ^1.0.6
  animate_do: ^4.2.0
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  path_provider: ^2.1.5
  flutter_expandable_fab: ^2.4.1
  flutter_gradient_animation_text: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/map_style.json


  fonts:
    - family: inter
      fonts:
        - asset: assets/fonts/inter.ttc
        - asset: assets/fonts/Inter-Black.ttf
          weight: 500
        - asset: assets/fonts/Inter-BoldItalic.ttf
          weight: 700
        - asset: assets/fonts/Inter-BoldItalic.ttf
          weight: 700
